### Producción:

### Ruta principal.
GET https://agenda-telefonica-backend-9m37.onrender.com

### Ruta para obtener todos los contactos de la agenda telefónica.
GET https://agenda-telefonica-backend-9m37.onrender.com/api/persons

### Ruta que proporciona info. 
GET https://agenda-telefonica-backend-9m37.onrender.com/info

### Ruta que devuelve los datos de una persona segun su id.
GET https://agenda-telefonica-backend-9m37.onrender.com/api/persons/1

### Ruta para eliminar una persona segun su id.
DELETE https://agenda-telefonica-backend-9m37.onrender.com/api/persons/1

### Agregar nuevas personas a la agenda telefónica.
POST https://agenda-telefonica-backend-9m37.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Prueba",
    "number": "123456"
}

### Desarrollo:

### Ruta principal.
GET http://localhost:10000

### Ruta para obtener todos los contactos de la agenda telefónica.
GET http://localhost:10000/api/persons

### Ruta que proporciona info. 
GET http://localhost:10000/info

### Ruta que devuelve los datos de una persona segun su id.
GET http://localhost:10000/api/persons/68dfcd4aadb03af6c9dbbe4c

### Ruta para eliminar una persona segun su id.
DELETE http://localhost:10000/api/persons/68dffd438d777fa6dec4bd2d

### Agregar nuevas personas a la agenda telefónica.
POST http://localhost:10000/api/persons
Content-Type: application/json

{
    "name": "Prueba2",
    "number": "123"
}

