### Ruta principal.
GET https://agenda-telefonica-backend-9m37.onrender.com

### Ruta que devuelve los datos codificados en JSON.
GET https://agenda-telefonica-backend-9m37.onrender.com/api/persons

### Ruta que proporciona info. 
GET https://agenda-telefonica-backend-9m37.onrender.com/info

### Ruta que devuelve los datos de una persona segun su id.
GET https://agenda-telefonica-backend-9m37.onrender.com/api/persons/1

### Ruta para eliminar una persona segun su id.
DELETE https://agenda-telefonica-backend-9m37.onrender.com/api/persons/1

### Agregar nuevas personas a la agenda telefónica.
POST https://agenda-telefonica-backend-9m37.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Prueba",
    "number": "123456"
}