### Producción:

### Ruta principal.
GET https://agenda-telefonica-backend-9m37.onrender.com

### Ruta para obtener todos los contactos de la agenda telefónica.
GET https://agenda-telefonica-backend-9m37.onrender.com/api/persons

### Ruta que proporciona info. 
GET https://agenda-telefonica-backend-9m37.onrender.com/info

### Ruta que devuelve los datos de una persona segun su id.
GET https://agenda-telefonica-backend-9m37.onrender.com/api/persons/1


### Desarrollo:

### Ruta para obtener todos los contactos de la agenda telefónica.
GET http://localhost:3001/api/persons

### Ruta que proporciona info. 
GET http://localhost:3001/info

### Ruta que devuelve los datos de una persona segun su id.
GET http://localhost:3001/api/persons/68e44b2ecc0c0a879b42d9dd

### Ruta para eliminar una persona segun su id.
DELETE http://localhost:3001/api/persons/68e44b2ecc0c0a879b42d9dd

### Agregar nuevas personas a la agenda telefónica.
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Prueba2",
    "number": "02-12345678"
}

### Ruta para actualizar una persona existente mediante su id.
PUT http://localhost:3001/api/persons/68e44c31cc0c0a879b42d9f0
Content-Type: application/json

{
    "name": "Prueba2",
    "number": "01-12345671"
}

